platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.4'

inputs:
- name: version

run:
  dir: version
  path: bash
  args:
  - -exc
  - |
    ls -al
    cat number

